name: My 4.0.0 test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*
  workflow_dispatch:

jobs:

  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      # Clone this repo
      
      - name: Checkout with number with v
        uses: ruchika-jain/checkout@v4.0.3
      
      
