name: My 4.0.0 test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:

  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      # Clone this repo
      - name: Checkout haha
        uses: ruchika-jain/checkout@4.0.0
