name: My non matrix 4.0.0 test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*
  workflow_dispatch:

jobs:

  test:
#     strategy:
#       matrix:
#         runs-on: [ubuntu-latest, macos-latest, windows-latest]
#     runs-on: ${{ matrix.runs-on }}
     runs-on: ubuntu-latest

     steps:
      # Clone this repo
      
      - name: Checkout with number without v
        uses: ruchika-jain/checkout@4.0.0
